name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run fix
      - run: yarn run build
      - name: Configure Git
        run: |
          git config --global user.name "fluteds"
          git config --global user.email "hi@dont-ban.me"
          git config --global credential.helper store
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: yarn run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
